# Project 1 - Car Price Prediction

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')

In [2]:
os.chdir('E:\\Sparsh\\Acmegrade Data Science\\Acmegrade Projects\\Sparsh Acmegrade Projects')
print(os.getcwd())

E:\Sparsh\Acmegrade Data Science\Acmegrade Projects\Sparsh Acmegrade Projects


## Reading Dataset

In [3]:
Audi_df=pd.read_csv('Audi.csv')
display(Audi_df.head())

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0    A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1    A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2    A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3    A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4    A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0

In [4]:
print('Number of rows:',Audi_df.shape[0])
print('Number of columns:',Audi_df.shape[-1])

Number of rows: 10668
Number of columns: 9


In [5]:
print('Data Types of each column:\n')
print(Audi_df.dtypes)

Data Types of each column:

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object


In [6]:
print('Checking null values.')
print(Audi_df.isna().sum())

Checking null values.
model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64


In [7]:
x=Audi_df.drop('price',axis=1).values
display(x)

array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [8]:
y=Audi_df[['price']].values
display(y)

array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

## Data Pre-processing

In [9]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
x[:,0]=le1.fit_transform(x[:,0])
le2=LabelEncoder()
x[:,4]=le1.fit_transform(x[:,4])
display(x)

array([[0, 2017, 'Manual', ..., 150, 55.4, 1.4],
       [5, 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [0, 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 'Manual', ..., 150, 49.6, 1.0],
       [9, 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [9, 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
Ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[2])],remainder='passthrough')
x=Ct.fit_transform(x)
display(x)

array([[0.0, 1.0, 0.0, ..., 150, 55.4, 1.4],
       [1.0, 0.0, 0.0, ..., 20, 64.2, 2.0],
       [0.0, 1.0, 0.0, ..., 30, 55.4, 1.4],
       ...,
       [0.0, 1.0, 0.0, ..., 150, 49.6, 1.0],
       [1.0, 0.0, 0.0, ..., 150, 47.9, 1.4],
       [0.0, 1.0, 0.0, ..., 150, 47.9, 1.4]], dtype=object)

In [11]:
display(pd.DataFrame(x))

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [12]:
from sklearn.preprocessing import StandardScaler
Sc=StandardScaler()
x=Sc.fit_transform(x)
display(pd.DataFrame(x))

0         1         2         3         4         5         6  \
0     -0.583268  1.200728 -0.712333 -1.123544 -0.046450 -0.386836  1.050783   
1      1.714479 -0.832828 -0.712333 -0.160831 -0.507834  0.483989 -0.954181   
2     -0.583268  1.200728 -0.712333 -1.123544 -0.507834  0.217781  1.050783   
3      1.714479 -0.832828 -0.712333 -0.545916 -0.046450  0.047853 -0.954181   
4     -0.583268  1.200728 -0.712333 -0.738459  0.876318 -0.971285  1.050783   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.885343  1.050783   
10664 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.972136  1.050783   
10665 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -1.030381  1.050783   
10666  1.714479 -0.832828 -0.712333  0.609339 -0.046450 -0.688442  1.050783   
10667 -0.583268  1.200728 -0.712333  0.609339 -0.507834 -0.551913  1.050783   

              7         8         9  
0      0.357147  0.357550 -0.880218  
1     -1.578323  1.037130  0.114925  
2     -1.429440  0.357550 -0.880218  
3      0.282706  1.276528  0.114925  
4      0.282706 -0.090355 -1.543647  
...         ...       ...       ...  
10663  0.282706 -0.090355 -1.543647  
10664  0.357147 -0.090355 -1.543647  
10665  0.357147 -0.090355 -1.543647  
10666  0.357147 -0.221637 -0.880218  
10667  0.357147 -0.221637 -0.880218  

[10668 rows x 10 columns]

## Train-Test Split

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)
print('X Shape:',x.shape)
print('X Train Shape:',x_train.shape)
print('X Test Shape:',x_test.shape)
print('Y Shape:',y.shape)
print('Y Train Shape:',y_train.shape)
print('Y Test Shape:',y_test.shape)


X Shape: (10668, 10)
X Train Shape: (8534, 10)
X Test Shape: (2134, 10)
Y Shape: (10668, 1)
Y Train Shape: (8534, 1)
Y Test Shape: (2134, 1)


## Model Creations

In [14]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error 
def Train(model,x,y,x_test,y_test):
    model.fit(x,y)
    print(f'Model:{model}')
    print()
    print('Model Report')
    print()
    y_pred = model.predict(x_test)   
    print('Predictions:\n',y_pred)
    print()
    print('Actual and Predicted Values:')
    print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))
    print()
    print('Accuracy:',r2_score(y_test,y_pred))    
    print()
    print('Mean Absolute Error:',mean_absolute_error(y_test,y_pred))
    print()
    print('Mean Square Error:',mean_squared_error(y_test,y_pred))


### Random Forest Regressor

In [15]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state=0)
Train(model,x_train,y_train,x_test,y_test)

Model:RandomForestRegressor(random_state=0)

Model Report

Predictions:
 [26789.2  17151.55 27509.9  ... 19662.98 16859.2  24257.9 ]

Actual and Predicted Values:
[[26789.2  28990.  ]
 [17151.55 16890.  ]
 [27509.9  26295.  ]
 ...
 [19662.98 18990.  ]
 [16859.2  16500.  ]
 [24257.9  23990.  ]]

Accuracy: 0.9603555134328308

Mean Absolute Error: 1495.120089121147

Mean Square Error: 5115967.37994611


### Linear Regression

In [16]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
Train(model,x_train,y_train,x_test,y_test)

Model:LinearRegression()

Model Report

Predictions:
 [[28897.67146213]
 [13745.67146213]
 [30375.67146213]
 ...
 [20133.67146213]
 [18987.67146213]
 [26649.67146213]]

Actual and Predicted Values:
[[28897.67146213 28990.        ]
 [13745.67146213 16890.        ]
 [30375.67146213 26295.        ]
 ...
 [20133.67146213 18990.        ]
 [18987.67146213 16500.        ]
 [26649.67146213 23990.        ]]

Accuracy: 0.7986825120366743

Mean Absolute Error: 3295.8934830813946

Mean Square Error: 25979241.7714393


### Extra Trees Regressor

In [17]:
from sklearn.ensemble import ExtraTreesRegressor
model=ExtraTreesRegressor(n_estimators = 120)
Train(model,x_train,y_train,x_test,y_test)

Model:ExtraTreesRegressor(n_estimators=120)

Model Report

Predictions:
 [26709.88333333 16696.44166667 27340.40833333 ... 19551.275
 16765.90833333 24710.375     ]

Actual and Predicted Values:
[[26709.88333333 28990.        ]
 [16696.44166667 16890.        ]
 [27340.40833333 26295.        ]
 ...
 [19551.275      18990.        ]
 [16765.90833333 16500.        ]
 [24710.375      23990.        ]]

Accuracy: 0.9583908909535972

Mean Absolute Error: 1519.3946576699122

Mean Square Error: 5369494.298516191


### Decision Tree Regressor

In [18]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()
Train(model,x_train,y_train,x_test,y_test)

Model:DecisionTreeRegressor()

Model Report

Predictions:
 [26800. 16992. 27840. ... 19450. 18575. 24451.]

Actual and Predicted Values:
[[26800. 28990.]
 [16992. 16890.]
 [27840. 26295.]
 ...
 [19450. 18990.]
 [18575. 16500.]
 [24451. 23990.]]

Accuracy: 0.9346873690024611

Mean Absolute Error: 1885.2365797146724

Mean Square Error: 8428341.961643027


### Naive Bayes Regressor

In [19]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
Train(model,x_train,y_train,x_test,y_test)

Model:GaussianNB()

Model Report

Predictions:
 [31970 19222 32250 ... 19560 22998 28445]

Actual and Predicted Values:
[[31970 28990]
 [19222 16890]
 [32250 26295]
 ...
 [19560 18990]
 [22998 16500]
 [28445 23990]]

Accuracy: 0.6726782458596324

Mean Absolute Error: 4095.7886597938145

Mean Square Error: 42239604.08950328


### Support Vector Regressor

In [25]:
from sklearn.svm import SVR
model=SVR(kernel='poly',C=1000)
Train(model,x_train,y_train,x_test,y_test)

Model:SVR(C=1000, kernel='poly')

Model Report

Predictions:
 [27687.82311075 16984.86960356 30024.30193771 ... 20974.78670607
 19716.44776624 22997.1126115 ]

Actual and Predicted Values:
[[27687.82311075 28990.        ]
 [16984.86960356 16890.        ]
 [30024.30193771 26295.        ]
 ...
 [20974.78670607 18990.        ]
 [19716.44776624 16500.        ]
 [22997.1126115  23990.        ]]

Accuracy: 0.9153258826866026

Mean Absolute Error: 2181.917660975844

Mean Square Error: 10926866.7502383


### K-Neighbors Regressor

In [26]:
from sklearn.neighbors import KNeighborsRegressor
model=KNeighborsRegressor()
Train(model,x_train,y_train,x_test,y_test)

Model:KNeighborsRegressor()

Model Report

Predictions:
 [[26292.8]
 [15575.2]
 [27885. ]
 ...
 [19283.6]
 [17172.4]
 [19995. ]]

Actual and Predicted Values:
[[26292.8 28990. ]
 [15575.2 16890. ]
 [27885.  26295. ]
 ...
 [19283.6 18990. ]
 [17172.4 16500. ]
 [19995.  23990. ]]

Accuracy: 0.9412949041108754

Mean Absolute Error: 1731.4868791002812

Mean Square Error: 7575665.158294285


### Randomized Search CV

In [27]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 60, stop = 1600, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]
rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf=RandomForestRegressor()
rcv=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=3,cv=3,random_state=42, n_jobs = 1)
display(rcv.fit(x_train,y_train))

rf_pred=rcv.predict(x_test)
print(rf_pred)

from sklearn.metrics import mean_absolute_error,mean_squared_error
print('Mean Absolute Error:',mean_absolute_error(y_test,rf_pred))
print()
print('Mean Square Error:',mean_squared_error(y_test,rf_pred))
print(r2_score(y_test,rf_pred))

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_iter=3, n_jobs=1,
                   param_distributions={'max_depth': [6, 15, 25, 35, 45],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [60, 231, 402, 573, 744,
                                                         915, 1086, 1257, 1428,
                                                         1600]},
                   random_state=42, scoring='neg_mean_squared_error')

[27269.7974876  16504.3712858  27986.27782097 ... 19488.46661393
 17438.25005365 23957.0064051 ]
Mean Absolute Error: 1465.709759126566

Mean Square Error: 4831486.370051191
0.9625600043409632
